springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /openapi/api.yaml
spring:
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/railway
    username: postgres
    password: APuurVCoxjEmEvufdKQz0oyviudG0aZy
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect